### ISSUE TITLE
default to registry-1.docker.io for docker.io

### ISSUE THREAD

**Issue by HannesHasselbring** [hmuendel/deputyl#1]
Correct the default to "https://registry-1.docker.io/" to support externaldns
from log
```
docker.io/bitnami/external-dns:0.5.15-debian-9-r46: Get "https://www.docker.com/v2/bitnami/external-dns/tags/list":
```
should call `https://registry-1.docker.io/v2/bitnami/external-dns/tags/list`

**Comment by hmuendel** [comment]
should be fixed with 11a98c6658bf7c242e1cdfceb27acc416a4b851b the exact default registry url can be configured via values.yaml
